const data = [
    {
        id: 1,
        img: 'shuhe1.jpg',
        marke: 'Nike Blazer Mid Suede',
        price: '129',
        count: 1,
    },
    {
        id: 2,
        img: 'shuhe2.jpg',
        marke: 'Nike Air Max 270',
        price: '109',
        count: 1,
    },
    {
        id: 3,
        img: 'shuhe3.jpg',
        marke: 'Under Armour Curry 8',
        price: '139',
        count: 1,
    },
    {
        id: 4,
        img: 'shuhe1.jpg',
        marke: 'Nike Kyrie 7',
        price: '149',
        count: 1,
    },
    {
        id: 5,
        img: 'shuhe4.jpg',
        marke: 'Jordan Air Jordan 11',
        price: '99',
        count: 1,
    },
    {
        id: 6,
        img: 'shuhe5.jpg',
        marke: 'Under Armour Curry',
        price: '199',
        count: 1,
    },
    {
        id: 7,
        img: 'shuhe6.jpg',
        marke: 'Nike Kyrie Flytrap IV',
        price: '139',
        count: 1,
    },
    {
        id: 8,
        img: 'shuhe7.jpg',
        marke: 'Jordan Air Jordan 11',
        price: '199',
        count: 1,
    },
    {
        id: 9,
        img: 'shuhe8.jpg',
        marke: 'Nike Lebron XVIII Low',
        price: '149',
        count: 1,
    },
    {
        id: 10,
        img: 'shuhe9.jpg',
        marke: 'Nike LeBron XVIII',
        price: '129',
        count: 1,
    },
]